version: "3.9"  # optional since v1.27.0
services:
  celery:
    build: .
    command: celery -A iska worker -l info --beat
    depends_on:
      - redis

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    depends_on:
      db:
         condition: service_healthy
      
    links:
      - db
  
  migration:
    build:  .
    command: python manage.py migrate --noinput
    depends_on:
      db:
         condition: service_healthy
  
  redis:
    image: redis

  db:
    image: postgis/postgis
    environment:
      - POSTGRES_DB=iska_ignitia_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5