# Generated by Django 4.0.2 on 2022-02-20 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='gid',
            field=models.IntegerField(db_index=True, unique=True),
        ),
    ]
