# Generated by Django 4.0.2 on 2022-02-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forecasts', '0002_alter_forecast_gid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forecast',
            name='lat',
            field=models.DecimalField(decimal_places=18, max_digits=21),
        ),
        migrations.AlterField(
            model_name='forecast',
            name='lon',
            field=models.DecimalField(decimal_places=18, max_digits=21),
        ),
    ]
