# Generated by Django 4.0.2 on 2022-02-20 18:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True)),
                ('original_sub_lan', models.CharField(choices=[('11', 'Daily'), ('21', 'Weekly'), ('0', 'Cancelled')], max_length=2)),
                ('sub_plan', models.CharField(choices=[('11', 'Daily'), ('21', 'Weekly'), ('0', 'Cancelled')], default='0', max_length=2)),
                ('msisdn', models.CharField(db_index=True, max_length=32)),
                ('lat', models.DecimalField(decimal_places=14, max_digits=17)),
                ('lon', models.DecimalField(decimal_places=14, max_digits=17)),
                ('is_active', models.BooleanField(default=True)),
                ('geom', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('lid', models.IntegerField(db_index=True, unique=True)),
                ('sub_date', models.DateTimeField()),
                ('unsub_date', models.DateTimeField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
