# Generated by Django 4.0.2 on 2022-02-20 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_alter_subscription_lat_alter_subscription_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='lid',
            field=models.IntegerField(),
        ),
    ]
