# Generated by Django 4.0.2 on 2022-02-22 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_subscription_billing_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='is_billed',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='send_sms',
        ),
    ]
